server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      soundcloud: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    visitorData: "CgtVaktKN0ZUS0ZOSSi8-4DQBjIKCgJVUxIEGgAgMmLfAgrcAjE4LllUPW9KUHJ0dFV4dlNVa2"
    clients:
      - WEB
      - ANDROID_TESTSUITE
      - MUSIC
  lavasrc:
    providers:
      - "ytmsearch:\"%ISRC%\""
      - "ytmsearch:%QUERY%"
      - "ytsearch:%QUERY%"
    sources:
      youtube: true
      youtubeMusic: true
logging:
  level:
    root: WARN
    lavalink: INFO
    io.netty: ERROR
    reactor.netty: ERROR
    org.springframework: ERROR