server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      soundcloud: true

logging:
  level:
    root: WARN
    lavalink: INFO
    dev.arbjerg.lavalink: INFO


logback:
    rollingpolicy:
      max-history: 1

logging:
  level:
    root: WARN
    lavalink: INFO
    dev.arbjerg.lavalink: INFO
    io.netty: ERROR
    reactor.netty: ERROR
    org.springframework: ERROR
    com.sedmelluq: WARN